### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by petrk94** [HiveCommons/Hive-Democracy#10]
Hello,

I would like to know how to use it

**Comment by lkngtn** [comment]
Hi @petrk94, The code in this repo was an initial attempt at creating a liquid democracy implementation and hasn't really be documented or tested. If you are interested in Liquid Democracy I would recommend getting involved with Aragon Labs Liquid Democracy working group. Check out this document for more information. :) https://docs.google.com/document/d/1fw_gpxaMsV-tJHpKz8jU22cciLBREQ5vB3T6nvvJbtU/edit#heading=h.jcmrpwsao2rg
