### ISSUE TITLE
Incentives for Voter Participation

### ISSUE THREAD

**Issue by lkngtn** [HiveCommons/Hive-Democracy#5]
**How can incentivize voter participation without compromising the integrity of the vote?**

Some suggestions which have been floated:

- No Artificial Incentive: Voters should not be incentivized to participate beyond their exercising their stake in governance. 
- A Vote Bounty: Users who want to see a vote decided on contribute to a pool, with the pool distributed to all voters after the fact. 
- A Vote Bounty for Winning Side: Same as above but instead of distributing the pool to all voters the bounty would be distributed only to the majority
- A Vote Bounty for Direct Voters: Same as above, but the bounty is distributed to only to people who participated directly rather than delegating their vote. 
- A Reward for Educated Voters based on a Screening Test: Users who are more informed about an issue would get a reward for voting

**Comment by lkngtn** [comment]
**Personally, I feel strongly that voter participation should not be rewarded by the system itself but recognize that all of these mechanisms could be implemented by a third party with no way to prevent it**. However, a third party would need to fund the bounties themselves so I think that becomes somewhat similar to lobbying.

Rather than focus on incentivizing participation in the actual vote, I think it's far more important to focus on incentivizing active and constructive debate and visibility of important issues and suggest instead that a "**Consensus Prediction Market**" be implemented to facilitate that. However, I think that is outside the scope of a liquid democracy implementation.

**Comment by timschloe** [comment]
Agree with you. Voting should be as easy as possible, but financial rewards seem to always have negative side effects.

I also have some deep philosophical concerns with prediction markets... Just after Galileo, I would have placed my bets on the consensus being the earth is flat for at least another 100 years, even if I saw and believed his evidence. Not sure if betting on the opinion of others is really the best option to find the truth. Seems more like a beauty contest of ideas and may be more strongly influenced by what I think people want to believe than what I think is true.

Something completely different, related to the original problem: One option I've been pondering for a while actually goes the other way... Assuming we have a stake-based voting system, the coin could be implemented in the form of a "steady stream" to every eligible ID, and leaving the option to spend as how coins on which decision to the user. Like that you can make your vote count more on issues important to you by abstaining from other issues. Would maybe add a decay to your coins, so you can't accumulate more than five years worth of decision coins or so. Been writing too much Sci-Fi, sorry if that's far out... :)

**Comment by lkngtn** [comment]
I agree with you that financial rewards often have negative side-effects, however, we also have to consider that in some cases these incentive systems are out of our control, as its possible for a third party to deploy a contract that creates those incentives and there is nothing that we could do about it. 

A consensus prediction market would incentivize debate rather than voting, and may have some unintended negative consequences (perhaps increasing the effect of demagoguery), though it would also have some positive effects as well, since it would encourage active participation and debate of issues based on a strong understanding of the will of the larger population. As you said this may not always result in the correct choice if the public is generally wrong, but will facilitate more active participation without encouraging negligent voting (for rewards), or restrict voting based on an arbitrary assessment of knowledge. 

Futarchy I think is perhaps a better solution to incentivized debate than a consensus prediction market without necessarily encouraging demagoguery but the premise is a bit more extreme since in that model users do not vote on specific issues, just on their general well being. 

Regarding the idea of users getting a voting allowance and spending that on given issues, is very much in line with the idea of Quadratic Vote Buying, and it's a really interesting topic and approach. I think its particularly useful in the context of Curation Markets and I've been researching how it might work in the context of 1Hive--It could potentially be layered on top of liquid democracy, but I think makes more sense in the context of direct voting.
